#! /bin/bash
FILE=/home/$USER/Documents/byebye.txt
if test -f "$FILE"; then
     echo "$FILE already exists."
else 
     echo "no log file exist"
     echo "creating a file... 'byebye.txt' "
     touch /home/$USER/Documents/byebye.txt
     echo "file created!"
fi
 date >> /home/$USER/Documents/byebye.txt
 uptime -p >> /home/$USER/Documents/byebye.txt
echo "Your system uptime is logged."
shutdown